### ISSUE TITLE
python exception running tldr test

### ISSUE THREAD

**Issue by blurdeblur** [adamewing/tldr#11]
I ran the test and got this error:

2021-02-03 15:17:21,431 te-ont started with command: /root/anaconda3/envs/R4/bin/tldr -b test.bam -e teref.human.fa -r ref.fa --color_consensus
2021-02-03 15:17:21,431 output basename: test
2021-02-03 15:17:21,658 writing clusters to test/chrTEST.pickle
2021-02-03 15:17:21,789 loaded 14 clusters from test/chrTEST.pickle
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/R4/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/R4/lib/python3.7/site-packages/tldr-0.1-py3.7.egg/EGG-INFO/scripts/tldr", line 1198, in process_cluster
  File "/root/anaconda3/envs/R4/lib/python3.7/site-packages/tldr-0.1-py3.7.egg/EGG-INFO/scripts/tldr", line 983, in minimap2_profile
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 947, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/R4/bin/tldr", line 4, in <module>
    __import__('pkg_resources').run_script('tldr==0.1', 'tldr')
  File "/root/anaconda3/envs/R4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/anaconda3/envs/R4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/root/anaconda3/envs/R4/lib/python3.7/site-packages/tldr-0.1-py3.7.egg/EGG-INFO/scripts/tldr", line 1811, in <module>
  File "/root/anaconda3/envs/R4/lib/python3.7/site-packages/tldr-0.1-py3.7.egg/EGG-INFO/scripts/tldr", line 1648, in main
  File "/root/anaconda3/envs/R4/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: file does not contain alignment data

I wonder if you can tell me what I did wrong?
Thank you,

**Comment by adamewing** [comment]
Sorry I missed this one, it's been ages but let me know if you've resolved this or not. My guess is a dependency might be missing (minimap2 maybe?)
