### ISSUE TITLE
Install erro

### ISSUE THREAD

**Issue by huangyuanf** [adamewing/tldr#16]
I have installed minimap2 by conda,but when I run python setup.py install ,I got such information:
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    if not check_minimap2(): sys.exit('Dependency problem: minimap2 >= 2.0 not found')
  File "setup.py", line 8, in check_minimap2
    p = subprocess.Popen(['minimap2', '--version'], stdout=subprocess.PIPE)
  File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'minimap2'

please help me

**Comment by adamewing** [comment]
Can you run `minimap2` by itself outside of tldr?

**Comment by huangyuanf** [comment]
&nbsp;thanks! Yes,I can run minimap2,but I can not install TLDR,my python version is Python 3.8.5,so I don know why.&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adamewing/tldr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adamewing/tldr] Install erro (#16)





 
Can you run minimap2 by itself outside of tldr?

**Comment by huangyuanf** [comment]
I have resolved the question.But when I run  /lustre/huangyf/software/tldr-1.2.2/tldr/tldr" --help ;I got information as following:
Traceback (most recent call last):
  File "/lustre/huangyf/software/tldr-1.2.2/tldr/tldr", line 17, in <module>
    from bx.intervals.intersection import Intersecter, Interval
ImportError: No module named bx.intervals.intersection

I try to conda install bx.intervals.intersection -y but failed,so how to resolve it .Thanks!

**Comment by adamewing** [comment]
The package name for that one is `bx-python` so try either `conda install -c bioconda bx-python` or `pip install bx-python`. Hope that helps.

**Comment by huangyuanf** [comment]
when I run tldr,I got such information,could you help me ,I have check the file exciting and I have installed 'exonerate' by conda,what's wrong .
Traceback (most recent call last):
  File "/lustre/huangyf/software/Miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 1270, in process_cluster
    te = te_align(te_lib, insread.r_seq_trimmed)
  File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 851, in te_align
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'exonerate'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 2083, in <module>
    main(args)
  File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 1873, in main
    processed_clusters.append(res.get())
  File "/lustre/huangyf/software/Miniconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'exonerate'

**Comment by huangyuanf** [comment]
First step ,I use conda installing minimap=2.21-r1071,exonerate=2.4.0,samtools=1.8,MAFFT v7.480, the path of all is /lustre/huangyf/software/Miniconda3/bin/ ;then I downloaded the tldr-1.2.2 .tar.gz  from this page , then I use tar -zxvf tldr-1.2.2 .tar.gz  and change directory to tldr-1.2.2 but when I run python setup.py install,I got such information:
Traceback (most recent call last):
File "setup.py", line 57, in
if not check_minimap2(): sys.exit('Dependency problem: minimap2 >= 2.0 not found')
File "setup.py", line 8, in check_minimap2
p = subprocess.Popen(['minimap2', '--version'], stdout=subprocess.PIPE)
File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 854, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'minimap2'

then I found if I copy minimap=22.21-r1071,exonerate=2.4.0,samtools=1.8,MAFFT v7.480 to tldr directory,I can install it ,but when I run I run tldr,I got such information:
Traceback (most recent call last):
File "/lustre/huangyf/software/Miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 1270, in process_cluster
te = te_align(te_lib, insread.r_seq_trimmed)
File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 851, in te_align
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 854, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/lustre/huangyf/software/Miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'exonerate'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 2083, in
main(args)
File "/lustre/huangyf/software/tldr/build/scripts-3.8/tldr", line 1873, in main
processed_clusters.append(res.get())
File "/lustre/huangyf/software/Miniconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'exonerate'

so,I don't known what's wrong?

**Comment by adamewing** [comment]
Are you able to run the commands for those tools (minimap2, exonerate, mafft) outside of tldr? If so, are you sure you're running tldr in the same environment and/or same machine as the dependencies?

**Comment by huangyuanf** [comment]
en,how can I make sure running tldr in the same environment and/or same machine as the dependencies? I don't understand this,what should I do?
