### ISSUE TITLE
Command-line options for tldr 3.2.0

### ISSUE THREAD

**Issue by Machadum** [adamewing/tldr#39]
Hi Adam,

I am using tldr 1.2.2 on my laptop but installed tldr 3.2.0 on my desktop Mac and the command-line options seem to have changed:
`tldr: error: unrecognized arguments:`
`--bams /Volumes/Rita/Pilot/Pilot.bam` 
`--chroms /Volumes/Rita/tldr/chrY.txt` 
`--elts none` 
`--ref /Volumes/Rita/Ext.datasets/References/ncbi_dataset/GCA_000001405.14_GRCh37.p13_genomic.fna` 
`--outbase Results_ALLbefore_chrY`

Could you please detail the new commands? 

Also what is the command to update tldr on my laptop? 
Many thanks!

**Comment by adamewing** [comment]
Hi, 1.2.2 is the latest, are you sure you haven't installed some other application called "tldr"?

**Comment by Machadum** [comment]
Oopsie yes it could be! Sorry for this. `pip install` did not work (please see below) so I instead did `conda install`

```
pip install -e $PWD

DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/threadpoolctl-3.5.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/Cython-3.0.10-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/joblib-1.4.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/scipy-1.14.0rc2-py3.12-macosx-11.1-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/bx_python-0.11.0-py3.12-macosx-11.1-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/scikit_learn-1.5.0-py3.12-macosx-11.1-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/ipmc/miniconda3/lib/python3.12/site-packages/numpy-2.0.0-py3.12-macosx-11.1-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Obtaining file:///Users/ipmc/miniconda3/envs/tldr
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/ipmc/miniconda3/envs/tldr/setup.py", line 57, in <module>
          if not check_minimap2(): sys.exit('Dependency problem: minimap2 >= 2.0 not found')
                 ^^^^^^^^^^^^^^^^
        File "/Users/ipmc/miniconda3/envs/tldr/setup.py", line 8, in check_minimap2
          p = subprocess.Popen(['minimap2', '--version'], stdout=subprocess.PIPE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/ipmc/miniconda3/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/ipmc/miniconda3/lib/python3.12/subprocess.py", line 1955, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'minimap2'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Machadum** [comment]
Hi again

I finally managed to install it on my new computer and it seems to work fine! Thank you for your prompt response.

**Comment by adamewing** [comment]
Good to know, hope it's useful for you!

**Comment by Machadum** [comment]
Yes I use tldr a lot!
